# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum hereon GmbH (hereon)#
# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FieContributor: Carsten Lemmen <carsten.lemmen@hereon.de>

stages:
  - lint
  - run
  - deploy

license-compliance:
    image: python:3.9
    stage: lint
    before_script:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install
    script:
        - poetry run reuse lint
    allow_failure: true

unit-tests:
  image: comses/netlogo # see https://github.com/comses/docker-netlogo
  stage: run
  script:
    - echo "Trying to run in working directory and headless mode"
    - echo "Java HOME is ${JAVA_HOME}"
    - cd ${CI_PROJECT_DIR}/netlogo
    - > 
      bash /opt/netlogo/netlogo-headless.sh 
      --model ./abm_fisheries_mussel.nlogo 
      --setup-file ./behavior/unit-tests.xml
      --experiment "unit-tests" --table -
  
create-map:
  image: comses/netlogo # see https://github.com/comses/docker-netlogo
  stage: run
  before_script:
    - echo "Nothing done here."
  script:
    - echo "Trying to run in working directory and headless mode"
    - echo "Java HOME is ${JAVA_HOME}"
    - cd ${CI_PROJECT_DIR}/netlogo
    - > 
      bash /opt/netlogo/netlogo-headless.sh 
      --model ./abm_fisheries_mussel.nlogo 
      --setup-file ./behavior/effort-map.xml
      --experiment "effort-map" --table -
  
  # Preserve resulting files
  artifacts:
    paths: 
      - ./netlogo/results/

pages: # predefined name by GitLab
    stage: deploy
    dependencies: 
        - create-map
    script:
        - mkdir -p public # required by GitLab
        - mv ./netlogo/results/*.png public/
        - touch public/index.html
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    artifacts:
        paths:
            - public/

joss-paper:
  stage: deploy
  image: 'openjournals/inara:latest'
  script:
    - inara -o pdf doc/joss/paper.md
  environment:
    name: draft
  variables:
    GIT_SHA: $CI_COMMIT_SHA
    JOURNAL: joss
  when: always
  allow_failure: false
  artifacts:
    paths:
      - doc/joss/paper.pdf
      - pdf
  dependencies:
  rules:
     - if: $CI_COMMIT_BRANCH == joss


