# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum hereon GmbH (hereon)#
# SPDX-License-Identifier: CC-BY-4.0
# Author: Carsten Lemmen <carsten.lemmen@hereon.de>

stages:
  - run

run:
  image: comses/netlogo # see https://github.com/comses/docker-netlogo
  stage: run
  before_script:
    - echo "Nothing done here."
  script:
    - echo "Trying to run in working directory and headless mode"
    - echo "Java HOME is ${JAVA_HOME}"
    - cd ${CI_PROJECT_DIR}/netlogo
    - bash /opt/netlogo/netlogo-headless.sh --model ./display-species-distribution.nlogo --experiment "test" --table -
