# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum hereon GmbH (hereon)#
# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FieContributor: Carsten Lemmen <carsten.lemmen@hereon.de>

include :
  - .gitlab/license.yaml
  - .gitlab/docker.yaml
  - .gitlab/joss.yaml
  - .gitlab/odd.yaml

stages:
  - lint
  - run
  - test
  - deploy

unit-tests:
  image: comses/netlogo # see https://github.com/comses/docker-netlogo
  stage: test
  script:
    - echo "Trying to run in working directory and headless mode"
    - echo "Java HOME is ${JAVA_HOME}"
    - cd ${CI_PROJECT_DIR}/netlogo
    - sed  -i 's/^NetLogo 6..../NetLogo 6.2.2/g' abm_fisheries_mussel.nlogo
    - > 
      bash /opt/netlogo/netlogo-headless.sh 
      --model ./abm_fisheries_mussel.nlogo 
      --setup-file ./behavior/unit-tests.xml
      --experiment "unit-tests" --table -
  
# create-map:
#   image: comses/netlogo # see https://github.com/comses/docker-netlogo
#   stage: run
#   before_script:
#     - echo "Nothing done here."
#   script:
#     - echo "Trying to run in working directory and headless mode"
#     - echo "Java HOME is ${JAVA_HOME}"
#     - cd ${CI_PROJECT_DIR}/netlogo
#     - > 
#       bash /opt/netlogo/netlogo-headless.sh 
#       --model ./abm_fisheries_mussel.nlogo 
#       --setup-file ./behavior/effort-map.xml
#       --experiment "effort-map" --table -
  
  # Preserve resulting files
  artifacts:
    paths: 
      - ./netlogo/results/
  needs: []

# The pages deployment only works on public projects, so we 
# have to wait past Milestone 1 to enable this feature. It
# is advertised in the JOSS paper, so needs to be implemented
# right away.
# pages: # predefined name by GitLab
#     stage: deploy
#     dependencies: 
#         - create-map
#     script:
#         - mkdir -p public # required by GitLab
#         - mv ./netlogo/results/*.png public/
#         - touch public/index.html
#     rules:
#         - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#     artifacts:
#         paths:
#             - public/
#     needs: []


