# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum hereon GmbH (hereon)#
# SPDX-License-Identifier: CC-BY-4.0
# Author: Carsten Lemmen <carsten.lemmen@hereon.de>

stages:
  - run
  - lint

license-compliance:
    image: python:3.9
    stage: lint
    before_script:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install
    script:
        - poetry run reuse lint
    allow_failure: true

test-target:
  image: comses/netlogo # see https://github.com/comses/docker-netlogo
  stage: run
  before_script:
    - echo "Nothing done here."
  script:
    - echo "Trying to run in working directory and headless mode"
    - echo "Java HOME is ${JAVA_HOME}"
    - cd ${CI_PROJECT_DIR}/netlogo
    - bash /opt/netlogo/netlogo-headless.sh --model ./abm_fisheries_mussel.nlogo --experiment "Default" --table -
  
