# SPDX-FileCopyrightText: 2022-2023 Helmholtz-Zentrum hereon GmbH (hereon)
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileContributor: Carsten Lemmen <carsten.lemmen@hereon.de
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: ['--maxkb=1000']
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
#-   repo: https://github.com/jumanjihouse/pre-commit-hooks
#    rev: master
#    hooks:
#    -   id: markdownlint
#-   repo: https://gitlab.com/smop/pre-commit-hooks
#    rev: master
#    hooks:
#    -   id: check-gitlab-ci
-   repo: https://github.com/Data-Liberation-Front/csvlint.rb
    rev: v1.2.0
    hooks:
      - id: csvlint
#-   repo: https://github.com/fsfe/reuse-tool
#    rev: v1.1.2
#    hooks:
#      - id: reuse
