# SPDX-FileCopyrightText: 2023-2024 Helmholtz-Zentrum hereon GmbH
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileContributor: Carsten Lemmen <carsten.lemmen@hereon.de

site_name: Viable North Sea
docs_dir: ./doc/mkdocs
theme: readthedocs
plugins:
  - search
#markdown_extensions:
#  - markdown_include.include:
#      base_path: .
#  - admonition
