# SPDX-FileCopyrightText: 2023-2024 Helmholtz-Zentrum hereon GmbH
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileContributor: Carsten Lemmen <carsten.lemmen@hereon.de>

FROM ubuntu:rolling

LABEL description="Latex/pandoc/joss document generator based on Ubuntu"
LABEL author="Carsten Lemmen <carsten.lemmen@hereon.de>"
LABEL license="CC0-1.0"
LABEL copyright="2023-2024 Helmholtz-Zentrum hereon GmbH"

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8

RUN apt-get update && apt-get install --no-install-recommends -y \
   make git \
   texlive-plain-generic texlive-fonts-recommended texlive-latex-extra \
   texlive-luatex texlive-fonts-extra fonts-hack fonts-open-sans \
   fonts-lmodern  citation-style-language-styles pandoc latexmk \
   openssl ca-certificates texlive-science wget dpkg

# Ubuntu distro contains a very outdated version of pandoc, so
# we pull the deb file and install it (it is a standalone binary)
RUN arch=$(uname -m) && \
  if [ "$arch" = "arm64" ]; then \
    echo "Running on arm64 architecture"; \
    wget -O pandoc.deb --no-check-certificate https://github.com/jgm/pandoc/releases/download/3.1.12.2/pandoc-3.1.12.2-1-arm64.deb ; \
  else \
    echo "Assume amd64 architecture"; \
    wget -O pandoc.deb --no-check-certificate https://github.com/jgm/pandoc/releases/download/3.1.12.2/pandoc-3.1.12.2-1-amd64.deb ; \
  fi
RUN dpkg -i pandoc.deb

# For this docker, emulate the behaviour of openjournals/inara, but
# create a bash entrypoint, not one running pandoc
RUN git clone --depth=1 https://github.com/openjournals/inara.git

ENV OPENJOURNALS_PATH=/usr/local/share/openjournals

RUN cp -r inara/resources ${OPENJOURNALS_PATH}
RUN cp -r inara/data ${OPENJOURNALS_PATH}/data
RUN cp inara/scripts/clean-metadata.lua ${OPENJOURNALS_PATH}
RUN cp inara/scripts/entrypoint.sh /usr/local/bin/joss
RUN ln -sf /usr/bin/pandoc /usr/local/bin/pandoc

ENV JOURNAL=joss

CMD [ "/bin/bash" ]
