# SPDX-FileCopyrightText: 2023 Helmholtz-Zentrum hereon GmbH
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileContributor: Carsten Lemmen <carsten.lemmen@hereon.de>

FROM ubuntu:rolling

ARG NETLOGO_VERSION=6.3.0

ENV LC_ALL=C.UTF-8 \
    LANG=C.UTF-8

ENV MODEL_NAME=vinos.nlogo
ENV NETLOGO_NAME=NetLogo-${NETLOGO_VERSION}
ENV NETLOGO_URL=https://ccl.northwestern.edu/netlogo/${NETLOGO_VERSION}/${NETLOGO_NAME}-64.tgz

RUN apt update && apt install -y \
  curl vim xserver-xorg \
  default-jdk \
  python3-poetry

RUN mkdir /opt/netlogo
RUN mkdir /model
RUN curl ${NETLOGO_URL} --output ${NETLOGO_NAME}-64.tgz
RUN tar xzf ${NETLOGO_NAME}-64.tgz -C /opt/netlogo --strip-components=1

RUN groupadd -g 1009 model
RUN useradd -d /home/model -s /bin/bash -m model -u 1009 -g 1009
USER model
ENV HOME /home/model

COPY ./data ${HOME}/data
COPY ./netlogo ${HOME}/netlogo
COPY ./LICENSES ${HOME}/LICENSES
COPY ./.reuse ${HOME}/.reuse
COPY ./ReadMe.md ${HOME}

#RUN sed -i 's/^NetLogo 6..../NetLogo '${NETLOGO_VERSION}'/g' ${HOME}/netlogo/${MODEL_NAME}

ENV JAVA_HOME=/usr
ENV PATH=${PATH}:/opt/netlogo

CMD /opt/netlogo/netlogo-gui.sh ${HOME}/netlogo/${MODEL_NAME}

#ENTRYPOINT ["/opt/netlogo/netlogo-headless.sh", \
# "--model", "/model/netlogo/${MODEL_NAME}", \
# "--table", "/model/netlogo/results/table-output.csv", \
# "--spreadsheet", "/model/netlogo/results/spreadsheet-output.csv"]

# To build the docker file, and run netlogo interactivley:
# `docker build -t netlogo .`
# docker run -i -v /tmp/.X11-unix:/tmp/.X11-unix --user="$(id --user):$(id --group)" -t ulogo
#docker run -i -v /tmp/.X11-unix:/tmp/.X11-unix -v ${HOME}/.Xauthority:/home/model/.Xauthority --user=model:model -e DISPLAY=${DISPLAY}  -t netlogo  /opt/netlogo/netlogo-gui.sh
# docker run -e DISPLAY=192.168.178.125:0 -t netlogo
# docker run --rm  -e DISPLAY=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}'):0 -t nlogo
