# SPDX-FileCopyrightText: 2023 Helmholtz-Zentrum hereon GmbH
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileContributor: Carsten Lemmen <carsten.lemmen@hereon.de>

ARG NETLOGO_VERSION=6.3.0
FROM platipodium/netlogo:${NETLOGO_VERSION}

ARG NETLOGO_VERSION

LABEL description="Viable North Sea (ViNoS) NetLogo model"
LABEL author="Carsten Lemmen <carsten.lemmen@hereon.de>"
LABEL license="CC0-1.0"
LABEL copyright="2023 Helmholtz-Zentrum hereon GmbH"

ENV LC_ALL=C.UTF-8 \
    LANG=C.UTF-8

ENV MODEL_NAME=vinos.nlogo
ENV NETLOGO_NAME=NetLogo-${NETLOGO_VERSION}

RUN groupadd -g 1009 model
RUN useradd -d /home/model -s /bin/bash -m model -u 1009 -g 1009
USER model
ENV HOME /home/model

COPY ./data ${HOME}/data
COPY ./assets ${HOME}/assets
COPY ./netlogo ${HOME}/netlogo
COPY ./LICENSES ${HOME}/LICENSES
COPY ./.reuse ${HOME}/.reuse
COPY ./ReadMe.md ${HOME}

#RUN sed -i 's/^NetLogo 6..../NetLogo '${NETLOGO_VERSION}'/g' ${HOME}/netlogo/${MODEL_NAME}

ENV PATH=${PATH}:/opt/netlogo/bin
CMD /opt/netlogo/netlogo-gui.sh ${HOME}/netlogo/${MODEL_NAME}

# docker run -i -v /tmp/.X11-unix:/tmp/.X11-unix --user="$(id --user):$(id --group)" -t ulogo
