# SPDX-FileCopyrightText: 2023-2024 Helmholtz-Zentrum hereon GmbH
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileContributor: Carsten Lemmen <carsten.lemmen@hereon.de>

ARG NETLOGO_VERSION=6.3.0
ARG TARGETARCH

FROM platipodium/jdk

ARG NETLOGO_VERSION

LABEL description="NetLogo image based on ubuntu:rolling/jdk"
LABEL author="Carsten Lemmen <carsten.lemmen@hereon.de>"
LABEL license="CC0-1.0"
LABEL copyright="2023 Helmholtz-Zentrum hereon GmbH"

ENV LC_ALL=C.UTF-8 \
    LANG=C.UTF-8

ENV NETLOGO_NAME=NetLogo-${NETLOGO_VERSION}
ENV NETLOGO_URL=https://ccl.northwestern.edu/netlogo/${NETLOGO_VERSION}/${NETLOGO_NAME}-64.tgz

RUN mkdir /opt/netlogo
RUN curl ${NETLOGO_URL} --output ${NETLOGO_NAME}-64.tgz
RUN tar xzf ${NETLOGO_NAME}-64.tgz -C /opt/netlogo --strip-components=1
RUN rm -f ${NETLOGO_NAME}-64.tgz

# Inject JVM options
RUN sed -i '16i JVM_OPTS+=("-Dsun.java2d.xrender=false")' /opt/netlogo/netlogo-gui.sh

CMD /bin/bash

# Execute this image with `docker run -i -t platipodium/netlogo:6.3.0`
