import pandas as pd
import sys
import datetime
import pathlib

def get_copyright_list(df: pd.DataFrame) -> list[str]:
    copyrights = set()
    for _, row in df.iterrows():
        try:
            copyright = row.get('FileCopyrightText').replace('<text>','').replace('</text>',
                '').replace('SPDX-FileCopyrightText: ','')
        except:
            pass
            continue
        copyrights.add(copyright)

    return sorted(list(copyrights))

def get_license_list(df: pd.DataFrame) -> list[str]:
    licenses = set()
    for _, row in df.iterrows():
        try:
            license = row['LicenseInfoInFile'].replace('LicenseRef-','')
        except:
            pass
            continue
        licenses.add(license)

    return sorted(list(licenses))


def format_reuse(df: pd.DataFrame) -> str:

    text = ''
    stem = ''
    licenses = set()
    for _, row in df.iterrows():

        path=pathlib.Path(row['FileName'])
        stem = path.stem

        try:
            license = row['LicenseInfoInFile'].replace('LicenseRef-','')
        except:
            print('Cannot identify license in row "{row}"')
            continue
        copyright = row.get('FileCopyrightText').replace('<text>','').replace('</text>',
                '').replace('SPDX-FileCopyrightText: ','')
        #print(f"{row['FileName']}:\nLicense: {row['LicenseInfoInFile']}\nCopyright: {copyright}\n")
        text += f"* {row['FileName']}:\nLicense: {license}\nCopyright: {copyright}\n\n"

    return text

def process_reuse() -> pd.DataFrame:

    text = sys.stdin.read()
    paragraphs = text.split("\n\n")
    data = {}

    for paragraph in paragraphs:
        lines = paragraph.strip().split("\n")
        if len(lines) < 1: continue

        try:
            first_word = lines[0].split()[0]
        except:
            continue

        if not first_word == "FileName:": continue
        first_value = lines[0].split()[1]

        # create a dictionary to store the values
        values = {}

        # loop through the lines and add the values to the dictionary
        # Need copyright_counter
        counters={}
        for line in lines:
            try:
              key, value = line.split(": ", 1)
              if key not in values:
                  counters[key] = 0
                  values[key] = value
              else:
                  counters[key] += 1
                  values[key] = values[key] + ', ' + value
            except:
              continue

        #print(first_value)
        # add the values dictionary to the data dictionary using the first word as the key
        data[first_value] = values


    return pd.DataFrame.from_dict(data, orient='index')

if __name__ == '__main__':

    df = process_reuse()
    formatted = format_reuse(df)
    print(f'''<!--
SPDX-FileCopyRightText: {datetime.date.today().year} Helmholtz-Zentrum hereon GmbH
SPDX-LicenseRef: CC0-1.0
SPDX-FileContributor: Carsten Lemmen <carsten.lemmen@hereon.de>
-->
''')
    print(f'''
> This file was autogenerated by {sys.argv[0]}, please do not edit by hand
To produce this content, run `reuse spdx | python {sys.argv[0]}

# Licenses used

The following licenses are used by this project.  You can find the full license text
in the  [LICENSES](./LICENSES/) folder:
''')

    licenses = get_license_list(df)
    for l in licenses:
        print(f' * {l}')

    print(f'''
## Copyright holders

The following organizations and individuals own copyrights to (parts of) this project.
You can find the full license text in the  [LICENSES](./LICENSES/) folder:
''')
    copyrights = get_copyright_list(df)
    for c in copyrights:
        print(f' * {c}')

    print(f'''
## License and copyright by file name

Each file carries a license attribution, please consult the following list to identify
the license applicable to an individual file:
''')

    print(formatted)
